// src/api/index.js

// Tus frases en formato JSON. Puedes añadir tantas como quieras.
const frases = [
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes.",
    "El único modo de hacer un gran trabajo es amar lo que haces.",
    "No cuentes los días, haz que los días cuenten.",
    "El futuro pertenece a aquellos que creen en la belleza de sus sueños.",
    "Sé el cambio que quieres ver en el mundo.",
    "La imaginación es más importante que el conocimiento.",
    "Nunca es demasiado tarde para ser lo que podrías haber sido.",
    "Si puedes soñarlo, puedes lograrlo.",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
    "Intenta no volverte un hombre de éxito, sino un hombre de valor.",
    "Tengo la teoría de que cuando uno llora, nunca llora por lo que llora, sino por todas las cosas por las que no lloró en su debido momento.",
    "Algún día encontraremos lo que estamos buscando. O quizás no. Quizás encontraremos algo mucho mejor",
    "Me gusta hablar con personas rotas, o que algún día lo estuvieron. Es grandioso ver cómo almas muertas se empeñan en seguir brillando.",
    "Mira en lo cursi que me has convertido, si esto no es amor, entonces soy un loco sin motivo.",
    "Que bonito fluye todo: Cuando voy de tu mano, cuando me miran tus ojos, cuando me cobijan tus abrazos, cuando me besan tus labios, cuando me quema tu piel.",
    "El éxito llega cuando decides dar el primer paso.",
    "Cada día es una nueva oportunidad para mejorar y crecer.",
    "La perseverancia es lo que convierte los fracasos en triunfos.",
    "Si crees que puedes, ya estás a medio camino.",
    "No esperes a que todo sea perfecto. Empieza ahora y hazlo posible.",
    "No se trata de si van a derribarte, se trata de si vas a levantarte cuando lo hagan",
    "Nadie puede hacerte sentir inferior sin tu consentimiento",
    "Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo",
    "El pesimista ve dificultades en cada oportunidad. El optimista ve oportunidades en cada dificultad",
    "Muchos piensan en cambiar el mundo, pero casi nadie piensa en cambiarse a sí mismo",
    "Si estás trabajando en algo que te importa de verdad, nadie tiene que empujarte: tu visión te empuja",
    "No tienes que ser grande para empezar. Pero tienes que empezar para poder ser grande",
    "Podemos sufrir muchas derrotas pero no debemos ser derrotados",
    "El momento en que quieres dejarlo es justo el momento en que tienes que seguir avanzando",
    "No esperes. Nunca va a ser el momento adecuado",
    "La creatividad es la inteligencia divirtiéndose",
    "La creatividad es la inteligencia divirtiéndose",
    "No esperes. Nunca va a ser el momento adecuado",
    "Si la vida te da limones, haz limonada",
    "El único modo de hacer un gran trabajo es amar lo que haces",
    "Nunca es demasiado tarde para ser lo que podrías haber sido",
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes",
    "No cuentes los días, haz que los días cuenten",
    "El futuro pertenece a quienes creen en la belleza de sus sueños",
    "La imaginación es más importante que el conocimiento",
    "La mejor venganza es un éxito masivo",
    "Sé el cambio que quieres ver en el mundo",
    "Lo único imposible es aquello que no intentas",
    "Cree que puedes y ya estás a medio camino",
    "La felicidad no es algo hecho. Viene de tus propias acciones",
    "Caerse siete veces y levantarse ocho",
    "No dejes que tu pasado ocupe todo tu presente",
    "Lo que importa no es lo que te ocurre, sino cómo reaccionas a ello",
    "A veces no conoces el valor de un momento hasta que se ha convertido en un recuerdo",
    "No es la muerte lo que debes temer, sino nunca empezar a vivir",
    "El que pasa el tiempo arrepintiéndose del pasado, pierde el presente y arriesga el futuro",
    "La vida es como montar en bicicleta. Para mantener el equilibrio tienes que avanzar",
    "La vida es en un 10% lo que te ocurre, y en un 90% cómo te lo tomas",
    "Camina hacia el sol y las sombras quedarán siempre tras de ti",
    "No pares cuando estés cansado. Para cuando hayas terminado",
    "Qué locura o desatino me lleva a contar las faltas ajenas, teniendo tanto que decir de las mías",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre",
    "Solo yo puedo cambiar mi vida. Nadie puede hacerlo por mí",
    "Hemos sido llamados para curar heridas, para unir lo que se ha separado, y para traer a casa a quienes han perdido su camino",
    "El mayor peligro para la mayoría de nosotros no es apuntar demasiado alto y fallar, sino apuntar demasiado bajo y acertar",
    "El que cree que lo sabe todo es incapaz de aprender",
    "La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto",
    "Si no te gusta algo, cámbialo. Si no puedes cambiarlo, cambia tu actitud",
    "No es verdad que las personas paren de perseguir sueños porque se hacen viejos. Se hacen viejos porque dejar de perseguir sueños",
    "La felicidad no ocurre por casualidad, sino por elección",
    "Hay dos grandes días en la vida de una persona –el día en que nacemos, y el día en que descubrimos para qué",
    "Cuando te levantes por la mañana piensa en qué privilegio es estar vivo, pensar, disfrutar, amar",
    "Si hay algo en nosotros verdaderamente divino, es la voluntad. Por ella afirmamos la personalidad, templamos el carácter, desafiamos la adversidad, reconstruimos el cerebro y nos superamos diariamente",
    "Solo el que intenta lo absurdo es capaz de conseguir lo que parecía imposible",
    "Concentra todos tus pensamientos en el trabajo que tienes entre manos. Los rayos del sol no encienden fuego hasta que los enfocas en un solo punto",
    "Cuanto más grande es la dificultad, más gloria hay en superarla",
    "Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, arrástrate, pero hagas lo que hagas sigue moviéndote hacia adelante",
    "La palabra ‘no’ solo significa que empieces otra vez en un nivel superior",
    "No he llegado tan lejos solo para llegar hasta aquí",
    "Si no puedes dejar de pensar en ello, no dejes de trabajar en ello",
    "Somos lo que hacemos de forma repetida. La excelencia no es un acto, sino un hábito",
    "En la vida no se trata de encontrarte a ti mismo. Se trata de inventarte a ti mismo",
    "Tu tiempo es limitado, no lo malgastes viviendo la vida de otro. No te dejes atrapar por el dogma",
    "No preguntes cuál es tu lugar en el mundo: siéntate en él",
    "El mayor logro es ser tú mismo en un mundo que continuamente trata de convertirte en otra cosa",
    "Nunca soñé con el éxito. Trabajé por él",
    "Nunca es demasiado tarde para ser lo que podrías haber sido",
    "El éxito es mi única opción, no el fracaso",
    "No es que tenga talento: estoy obsesionado",
    "Demasiada gente no vive sus sueños porque está ocupada viviendo sus miedos",
    "Solo aquellos que se arriesgan a caer pueden conseguir grandes cosas",
    "Generamos miedos cuando estamos sentados. Y los superamos con la acción",
    "No mires hacia atrás –no es allí adonde vas",
    "Avanza con confianza en la dirección de tus sueños",
    "Saber qué es lo correcto y no hacerlo es falta de valor",
    "Todo lo que siempre deseaste está al otro lado del miedo",
    "La inacción produce duda y miedo. La acción genera confianza y valor. Si quieres dominar el miedo no te quedes en casa pensando sobre ello: sal fuera y enfréntate a él",
    "Tienes que hacer las cosas que crees que no puedes hacer",
    "Tu vida se encoge o se expande en proporción a tu valor",
    "Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo cuando intentas algo nuevo",
    "He aprendido que el valor no es la ausencia de miedo, sino el triunfo sobre él. El hombre valiente no es el que no siente miedo, sino el que lo domina",
    "Es imposible vivir sin fracasar en algo, a no ser que vivas con tanto cuidado que dé igual si has vivido o no –en cuyo caso, ya has fracasado",
    "El carácter no puede desarrollarse en la calma y en la facilidad. Solo a través de la experiencia y del sufrimiento se fortalece el alma, se inspira la ambición, y se alcanza el éxito",
    "Lo que cuenta no es de dónde vienes, sino adónde vas",
    "Sólo se vive una vez. Pero si lo haces bien, una vez basta",
    "Nunca, nunca, nunca abandones",
    "La fuerza no procede de la capacidad física, sino de una voluntad indomable",
    "No tienes poder sobre los acontecimientos exteriores –pero sí sobre tu mente. Aprende esto, y encontrarás tu fuerza",
    "El hombre que se levanta es más grande que el que nunca ha caído",
    "La mejor almohada para dormir es una conciencia tranquila",
    "El arte de vencer se aprende en las derrotas",
    "Olvida siempre a tus enemigos: nada les molesta más",
    "El conocimiento es poder",
    "La buena vida es una forma de pensar",
    "Solo quien se maneja a sí mismo puede manejar a los demás",
    "Ser positivo no significa que todo vaya a salir bien. Significa saber que vas a estar bien independientemente de cómo salgan las cosas",
    "Todos los hombres que no tienen nada importante que decir hablan a gritos",
    "Tenemos dos orejas y una boca para escuchar el doble de lo que hablamos",
    "Un campeón se distingue no por sus victorias, sino por cómo se recupera de sus derrotas",
    "Aferrarse al rencor es como beber veneno y esperar que otra persona muera",
    "Una persona inteligente resuelve los problemas. Una persona sabia los evita",
    "A menudo las dificultades preparan a una persona normal para un destino extraordinario",
    "Dentro de veinte años estarás más arrepentido por las cosas que no hiciste que por aquellas que hiciste",
    "La perseverancia a pesar de todos los obstáculos, desánimos e imposibilidades: esto es lo que distingue el alma fuerte de la débil",
    "Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que te importa de verdad se llama pasión",
    "Recuerda que, a veces, no conseguir lo que quieres es un gran golpe de suerte",
    "Para tener éxito la actitud es tan importante como la habilidad",
    "Hecho es mejor que perfecto",
    "En ese lugar entre tu zona de confort y tu sueño es donde está la verdadera vida",
    "Empieza haciendo lo que es necesario; después haz lo que es posible; y pronto te encontrarás haciendo lo imposible",
    "Las frases motivadoras pueden inspirarte; pero es la acción la que te completa",
    "Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta",
    "Más que producto de mis circunstancias, soy producto de mis decisiones",
    "La cuestión no es quién va a permitírmelo, sino quién va a ser capaz de pararme",
    "La acción es la verdadera medida de la inteligencia",
    "La perfección es imposible. Pero si aspiramos a ella podemos alcanzar la excelencia",
    "Sé tan bueno que no puedan ignorarte",
    "La Fortuna ayuda a los audaces",
    "No podemos resolver nuestros problemas con el mismo razonamiento que usamos cuando los creamos",
    "Vive como si fueras a morir mañana; aprende como si fueras a vivir siempre",
    "Aléjate de la gente que trata de empequeñecer tus ambiciones. La gente pequeña siempre hace eso, pero la gente realmente grande, te hace sentir que tú también puedes ser grande",
    "Cuando haces feliz a otras personas, recibes más felicidad a cambio. Deberías meditar bien sobre cuánta felicidad eres capaz de dar",
    "Cambia tus pensamientos y cambiarás tu mundo",
    "Solo al arriesgarnos podemos hacer que nuestras vidas mejoren. El principal riesgo y el más difícil de asumir es ser honestos",
    "La naturaleza nos ha dado las piezas necesarias para alcanzar una riqueza y un bienestar excepcionales, pero nos ha dejado la tarea de juntarlas",
    "El éxito no es la clave de la felicidad. La felicidad es definitivo; el fracaso no es fatal. Lo que realmente cuenta es tener valor para continuar",
    "Es mejor fallar en un intenton la originalidad que triunfar en la imitación",
    "El camino hacia el éxito y el camino hacia el fracaso son prácticamente el mismo",
    "El éxito suele llegar a quienes están demasiado ocupados para buscarlo",
    "Desarrolla el éxito a partir de los fracasos. El desaliento y el fracaso son los peldaños hacia el éxito",
    "Nada en este mundo puede tomar el lugar de la persistencia. El talento no lo hará; nada es más común que los hombres sin éxito y con talento. El genio no lo hará; que los genios no son recompensados es casi proverbial. La educación tampoco: el mundo está lleno de negligentes educados. El lema «Sigue adelante» ha resuelto y resolverá siempre los problemas de la raza humana",
    "Hay tres caminos hacia el éxito definitivo. El primero es ser amable. El segundo es ser amable. El tercero es ser amable",
    "El éxito es la paz interior que resulta directamente de la autosatisfacción de saber que has hecho el esfuerzo de convertirte en lo mejor que eras capaz de ser",
    "Nunca he soñado con el éxito. He trabajado por él",
    "El éxito es obtener lo que quieres; la felicidad es querer lo que obtienes",
    "Concentra todos tus pensamientos sobre el trabajo en una mano. Los rayos del sol no queman hasta que hacen foco",
    "O corres durante el día o el día corre por ti",
    "Creo profundamente en la suerte: cuanto más duro trabajo, más suerte tengo",
    "Cuando nos esforzamos en ser mejores de lo que somos, todo a nuestro alrededor mejora también",
    "La mayoría de la gente pierde la oportunidad porque esta va vestida con un mono y parece trabajo",
    "Fijarse metas es el primer paso para transformar lo invisible en visible",
    "Tu trabajo va a suponer gran parte de tu vida, y la única forma de estar plenamente satisfecho es creer que se trata de un gran trabajo. El único modo de hacer un gran trabajo es amar lo que haces. Si aún no lo has encontrado, sigue buscando. No te conformes. Como sucede con todos los asuntos del corazón, cuando lo hayas encontrado te darás cuenta",
    "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos",
    "Del compromiso individual al esfuerzo de un equipo. Eso hace que un equipo funcione, que una compañía funcione, que una sociedad y civilización funcionen",
    "El trabajo en equipo es la capacidad de trabajar juntos hacia una visión común. La habilidad de dirigir logros individuales hacia objetivos organizacionales. Es el combustible que permite a gente común alcanzar resultados poco comunes",
    "Aunarse es el principio. Mantenerse juntos, es el progreso. Trabajar juntos es el éxito",
    "Solos podemos hacer muy poco, juntos podemos hacer mucho",
    "Recuerda: el trabajo en equipo comienza construyendo confianza, y la única forma de hacerlo es superando nuestra necesidad de invulnerabilidad",
    "Invito a todo el mundo a elegir el perdón en lugar de la división, el trabajo en equipo en lugar de la ambición personal",
    "Solo un pequeño pensamiento positivo por la mañana puede cambiar todo tu día",
    "Las oportunidades no aparecen, las creas",
    "Ama a tu familia, trabaja muy duro, vive tu pasión",
    "Nunca es demasiado tarde para ser lo que podrías haber sido",
    "No dejes que la opinión de alguien sobre ti se convierta en tu realidad",
    "Si no eres energía positiva, eres energía negativa",
    "No soy un producto de mis circunstancias. Soy un producto de mis decisiones",
    "Hazlo lo mejor que puedas. Nadie puede hacer más que eso",
    "Si puedes imaginarlo, puedes hacerlo",
    "Haz lo que puedas, con lo que tienes, dondequiera que estés",
    "El gran descubrimiento de mi generación es que los seres humanos pueden cambiar sus vidas cambiando su actitud",
    "Una de las diferencias entre algunas personas de éxito y otras que no lo tienen es que un grupo está lleno de hacedores, mientras que el otro está lleno de deseadores",
    "Prefiero arrepentirme de las cosas que he hecho, que arrepentirme de las que no he hecho",
    "No puedes arar un campo dándole vueltas en tu mente. Para empezar, empieza",
    "Cuando te levantes por la mañana, piensa en el privilegio de vivir: respirar, pensar, disfrutar, amar",
    "Los lunes ofrecen un nuevo comienzo 52 veces al año",
    "Siéntete miserable. O motívate. Cualquier cosa que hagas será siempre decisión tuya",
    "Tus pensamientos del lunes por la mañana marcan la pauta de toda la semana. Visualízate siendo más fuerte y viviendo una vida más plena, feliz y saludable",
    "¡Los viernes se ven más sonrisas que cualquier otro día de la semana!",
    "¡Oh! Es viernes otra vez. Comparte el amor que te faltó durante la semana. Es un momento de paz y felicidad",
    "Cada viernes me gusta felicitarme por haber pasado otra semana con poco más que cafeína, fuerza de voluntad y humor inadecuado",
    "Haz que los viernes sean un día para celebrar el trabajo bien hecho, un trabajo del que puedas estar orgulloso de saber que simplemente no estás haciendo tiempo hasta el próximo día de pago",
    "Cuando dejes de trabajar el viernes, deja de trabajar. No permitas que la tecnología te siga todo el fin de semana (respondiendo emails y mensajes de texto). Tómate un descanso. Estarás más fresco para empezar la nueva semana laboral si te has tomado un descanso",
    "No mires a tus pies para ver si lo estás haciendo bien. Simplemente, baila",
    "Alguien está sentado hoy a la sombra porque alguien plantó un árbol hace mucho tiempo",
    "La verdadera libertad es imposible sin una mente liberada por la disciplina",
    "Los ríos lo saben: no hay prisa. Algún día llegaremos",
    "Existe una vitalidad, una fuerza de vida, una energía, una urgencia que a través de ti se traduce en acción, y puesto que solo hay una como tú, esta expresión es única. Si la bloqueas, nunca existirá a través de ningún otro medio y se perderá",
    "Lo pequeño es algo más que un paso en el camino. Es un destino en sí mismo",
    "El que puede tener paciencia, puede tener lo que quiera",
    "La única persona que puede decirte ‘no puedes lograrlo’ eres tú misma, y no debes escucharla",
    "Fíjate unas metas altas, y no te detengas hasta alcanzarlas",
    "Acepta tus victorias, sean las que sean, valóralas, úsalas, pero no te conformes con ellas",
    "El miedo a lo que pensarán los demás es la dinámica más paralizante en los negocios y en la vida. El mejor momento de mi vida fue el día en que me di cuenta de que me importaba un bledo lo que pensaran los demás. Es enormemente liberador, y es la única manera de vivir tu vida y sacar adelante tu negocio",
    "La única manera de descubrir los límites de lo posible es aventurarse un poco más allá de ellos hacia lo imposible",
    "La preocupación es un mal uso de la imaginación",
    "La valentía es la más importante de todas las virtudes, porque sin valentía no puedes practicar ninguna otra virtud de manera constante",
    "Nunca miro atrás, querido. Me distrae del ahora",
    "De aquí a un año desearás haber empezado hoy",
    "La razón por la que luchamos contra la inseguridad es porque comparamos nuestra vida privada con el lado notable de los demás",
    "En algún lugar hay algo increíble en espera de ser descubierto",
    "No perderé, porque incluso en la derrota, se aprende una lección valiosa, así que existe un equilibrio",
    "No intento bailar mejor que nadie más. Solo intento bailar mejor que yo misma",
    "Si no arriesgas nada, arriesgas aún más",
    "El fracaso no es más que una oportunidad de volver a empezar, esta vez de un modo más inteligente",
    "Nuestra mayor gloria no es no haber caído nunca, sino levantarnos cada vez que caemos",
    "Si cambias la forma en que miras las cosas, las cosas que miras cambian",
    "Debemos ofrecer nuestra mano con amistad y dignidad, tanto a quienes se harían amigos nuestros como a quienes podrían convertirse en nuestros enemigos",
    "Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso",
    "El fracaso no es más que una oportunidad de volver a empezar, esta vez de un modo más inteligente",
    "Nuestra mayor gloria no es no haber caído nunca, sino levantarnos cada vez que caemos",
    "Si cambias la forma en que miras las cosas, las cosas que miras cambian",
    "Debemos ofrecer nuestra mano con amistad y dignidad, tanto a quienes se harían amigos nuestros como a quienes podrían convertirse en nuestros enemigos",
    "Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso",
    "Asegúrate de que tu peor enemigo no vive entre tus dos orejas",
    "Es duro el camino que conduce a la grandeza",
    "Lo grandioso no sucede solo por impulso, es una sucesión de pequeñas cosas que se juntan",
    "Si cuidamos los pequeños momentos, los años cuidarán de nosotros",
    "Resiliencia es afrontar la incertidumbre con flexibilidad",
    "A veces la magia es simplemente alguien dedicándole más tiempo a algo de lo que cualquiera podría esperar",
    "Lo que importa no es la voluntad de ganar, todo el mundo la tiene. Lo que importa es la voluntad de prepararse para ganar",
    "Así como un solo paso no abrirá un camino en la tierra, un solo pensamiento no abrirá un camino en la mente. Para hacer un camino físico profundo, caminamos una y otra vez. Para trazar un camino mental profundo, debemos pensar una y otra vez el tipo de pensamientos que deseamos que dominen nuestras vidas",
    "Nunca renuncies a un sueño simplemente por el tiempo que necesitarás para lograrlo. El tiempo pasará de todos modos",
    "La verdadera humildad no es pensar menos de uno mismo: es pensar menos en sí mismo",
    "Los dos días más importantes de tu vida son el día en el que naces y el día en el que descubres por qué",
    "Nada desaparece hasta que nos enseña lo que necesitamos saber",
    "Podemos ver a través de los demás solo cuando podemos ver a través de nosotros mismos",
    "Olvídate de la inspiración. Fíate más del hábito. El hábito te sostendrá, tanto si estás inspirado como si no",
    "La mejor salida es siempre a través",
    "Las batallas que cuentan no son las de las medallas de oro. La lucha interior, las batallas invisibles e inevitables dentro de uno mismo, son las que cuentan",
    "Sin lucha no hay progreso",
    "Alguien siempre dirá ‘Yo soy el líder’, y esperará que todos hagan una fila y lo sigan hasta las puertas del cielo o del infierno. Pero la experiencia me dice que eso no sucede así. Los demás te siguen por la calidad de tus acciones, más que por la magnitud de tus palabras",
    "La valentía es como un músculo. La fortalecemos con el uso",
    "Corta por lo sano con las tonterías, no esperes a hacer lo que verdaderamente importa y saborea el tiempo que tienes. Es lo que debes hacer porque la vida es corta",
    "Más se pierde por la indecisión que por una mala decisión",
    "Si el principal objetivo del capitán fuera preservar su barco, lo mantendría en el puerto para siempre",
    "Ya puedes ser el melocotón más maduro y jugoso del mundo, que siempre habrá alguien que odie los melocotones",
    "Mantén un poco de fuego encendido: por pequeño que sea y por oculto que esté",
    "La persistencia es el camino al éxito",
    "Cada día es una nueva oportunidad para brillar",
    "Tu actitud determina tu dirección",
    "Sé la razón por la que alguien sonríe hoy",
    "El único límite es tu mente",
    "Cree en ti mismo y todo será posible",
    "Haz de cada día una obra maestra",
    "Nunca dejes de aprender, porque la vida nunca deja de enseñar",
    "La felicidad es una elección, no un resultado",
    "Siembra hoy lo que quieras cosechar mañana",
    "El éxito no es el final, el fracaso no es fatal: es el coraje para continuar lo que cuenta",
    "Los sueños no funcionan a menos que tú lo hagas",
    "La vida es un eco; lo que envías, vuelve",
    "No busques el momento perfecto, hazlo perfecto",
    "La mejor manera de predecir el futuro es crearlo",
    "La paciencia es amarga, pero sus frutos son dulces",
    "Pequeñas acciones, grandes resultados",
    "El cambio es la única constante en la vida",
    "La simplicidad es la clave de la brillantez",
    "Inspírate en los demás, pero compite contigo mismo",
    "El dolor es temporal, la gloria es para siempre",
    "El propósito de nuestras vidas es ser felices",
    "No te compares, sé único",
    "La risa es el mejor remedio",
    "La creatividad es contagiosa, pásala",
    "Cada paso cuenta en el camino hacia tus metas",
    "El miedo es una ilusión, el coraje es real",
    "La gratitud transforma lo que tenemos en suficiente",
    "Sé agradecido por lo que tienes y lucha por lo que quieres",
    "El futuro empieza hoy",
    "La vida es corta, sonríe mientras tengas dientes",
    "No se trata de la meta, sino del viaje",
    "Las dificultades son oportunidades disfrazadas",
    "El éxito ama la velocidad",
    "Tu única competencia eres tú mismo",
    "La verdadera riqueza está en la salud y la paz mental",
    "Sé valiente, asume riesgos, no hay sustituto para la experiencia",
    "La grandeza reside en las pequeñas cosas",
    "Si puedes soñarlo, puedes lograrlo",
    "El respeto se gana, la honestidad se aprecia, la confianza se adquiere, la lealtad se devuelve",
    "La clave no es priorizar lo que está en tu agenda, sino agendar tus prioridades",
    "Haz que hoy sea increíble",
    "No busques la felicidad, créala",
    "La vida es un regalo, desempaquétalo con alegría",
    "Invierte en ti mismo, es tu mejor activo",
    "La energía fluye donde va la atención",
    "Lo que te hace feliz, eso es el éxito",
    "No hay atajos para ningún lugar que valga la pena ir",
    "El fracaso es un trampolín, no un obstáculo",
    "La disciplina es el puente entre metas y logros",
    "Sé la luz en la oscuridad",
    "Aprende del pasado, vive el presente, sueña con el futuro",
    "El trabajo duro vence al talento cuando el talento no trabaja duro",
    "La mente es todo. Lo que piensas, te conviertes",
    "La vida es 10% lo que te pasa y 90% cómo reaccionas a ello",
    "Cada error es una lección disfrazada",
    "El coraje es ir de fracaso en fracaso sin perder el entusiasmo",
    "Tu tiempo es limitado, no lo malgastes viviendo la vida de otra persona",
    "El verdadero crecimiento comienza al final de tu zona de confort",
    "La bondad es un lenguaje que los sordos pueden oír y los ciegos pueden ver",
    "No dejes que el ayer ocupe demasiado de hoy",
    "La calidad no es un acto, es un hábito",
    "La fe mueve montañas",
    "Sé tú mismo; todos los demás puestos ya están ocupados",
    "La simplicidad es la máxima sofisticación",
    "No te rindas, el principio es siempre lo más difícil",
    "La mayor aventura que puedes tomar es vivir la vida de tus sueños",
    "El secreto del cambio es enfocar toda tu energía no en luchar contra lo viejo, sino en construir lo nuevo",
    "La mejor vista viene después de la subida más difícil",
    "Un optimista ve una oportunidad en cada calamidad; un pesimista ve una calamidad en cada oportunidad",
    "Si quieres ir rápido, ve solo. Si quieres llegar lejos, ve acompañado",
    "La paciencia es la compañera de la sabiduría",
    "La acción es la clave fundamental para todo éxito",
    "La vida es lo que tú haces de ella",
    "El conocimiento es poder, pero el entusiasmo es la llave",
    "Empieza donde estás. Usa lo que tienes. Haz lo que puedas",
    "No es lo que miras lo que importa, es lo que ves",
    "La educación es el arma más poderosa que puedes usar para cambiar el mundo",
    "Haz cada día algo que te asuste",
    "No hay sustituto para el trabajo duro",
    "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra",
    "La mejor manera de salir es siempre a través",
    "Lo único que se interpone entre ti y tu sueño es la voluntad de intentarlo y la creencia de que es realmente posible",
    "La vida no se mide por las veces que respiras, sino por los momentos que te quitan el aliento",
    "La gente olvidará lo que dijiste, la gente olvidará lo que hiciste, pero la gente nunca olvidará cómo les hiciste sentir",
    "No hay ascensor hacia el éxito, tienes que tomar las escaleras",
    "La oportunidad baila con los que ya están en la pista de baile",
    "El camino hacia el éxito siempre está en construcción",
    "La alegría está en la búsqueda, no en el hallazgo",
    "Lo que no te mata, te hace más fuerte",
    "El mañana es una nueva oportunidad para hacerlo mejor",
    "Haz tu propio camino",
    "La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra",
    "Cada día es un buen día para estar vivo",
    "Cualquier cosa que la mente del hombre pueda concebir y creer, puede lograrlo",
    "El valor no es la ausencia de miedo, sino el triunfo sobre él",
    "No es lo que haces, sino cómo lo haces",
    "El crecimiento es opcional. La supervivencia no lo es",
    "La imaginación es el principio de la creación",
    "La vida es como una cámara. Enfócate en lo importante. Captura los buenos momentos. Desarrolla a partir de los negativos. Y si las cosas no funcionan, toma otra toma",
    "La meta de la vida es dar valor, no solo existir",
    "Donde hay una voluntad, hay un camino",
    "No hay fracasos, solo lecciones",
    "El éxito no es para los que lo quieren, sino para los que lo trabajan",
    "La sonrisa es el idioma universal de la bondad",
    "Sé el protagonista de tu propia historia",
    "Lo imposible es solo una palabra grande lanzada por hombres pequeños que encuentran más fácil vivir en el mundo que se les ha dado que explorar el poder que tienen para cambiarlo",
    "La vida es un lienzo en blanco, y tú eres el artista",
    "Un día sin risa es un día perdido",
    "No cuentes los días, haz que los días cuenten",
    "El futuro pertenece a quienes creen en la belleza de sus sueños",
    "El mundo es un libro y aquellos que no viajan solo leen una página",
    "Las grandes mentes discuten ideas; las mentes promedio discuten eventos; las mentes pequeñas discuten personas",
    "La inspiración existe, pero tiene que encontrarte trabajando",
    "La mejor venganza es un éxito masivo",
    "La buena suerte es lo que sucede cuando la preparación se encuentra con la oportunidad",
    "Nunca es tarde para un nuevo comienzo",
    "La paciencia es un árbol de raíz amarga pero de frutos muy dulces",
    "Los desafíos son lo que hacen la vida interesante y superarlos es lo que hace la vida significativa",
    "La vida es un 10% lo que me pasa y un 90% cómo reacciono a ello",
    "El mayor riesgo es no correr ningún riesgo",
    "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía",
    "El valor es saber lo que no debes temer",
    "Lo que piensas, lo serás. Lo que sientes, lo atraerás. Lo que imaginas, lo crearás",
    "La vida es una obra de teatro que no permite ensayos. Por eso, canta, ríe, baila, llora y vive intensamente cada momento de tu vida… antes de que el telón baje y la obra termine sin aplausos",
    "La vida es realmente simple, pero insistimos en hacerla complicada",
    "No es el viento lo que determina la dirección, sino la posición de las velas",
    "El cambio es doloroso, pero nada es tan doloroso como quedarse atascado en algún lugar al que no perteneces",
    "Tu vida es tu mensaje al mundo. Asegúrate de que sea inspirador",
    "La disciplina es la madre del éxito",
    "Un viaje de mil millas comienza con un solo paso",
    "El genio es 1% inspiración y 99% transpiración",
    "La suerte es lo que pasa cuando la preparación se encuentra con la oportunidad",
    "No te preocupes por los fracasos, preocúpate por las posibilidades que pierdes cuando ni siquiera lo intentas",
    "La felicidad no es algo hecho. Viene de tus propias acciones",
    "Lo único imposible es aquello que no intentas",
    "Cada día es una página en blanco, escribe una buena historia",
    "La vida es como andar en bicicleta. Para mantener el equilibrio, debes seguir moviéndote",
    "La mejor manera de empezar es dejar de hablar y empezar a hacer",
    "La única forma de hacer un gran trabajo es amar lo que haces",
    "No busques errores, busca soluciones",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día",
    "La grandeza no es un lugar al que ir, es un viaje en el que te encuentras",
    "Las estrellas no pueden brillar sin oscuridad",
    "El secreto de la existencia humana no solo está en vivir, sino también en saber para qué se vive",
    "El trabajo duro siempre da sus frutos",
    "Nunca se es demasiado viejo para establecer otra meta o para soñar un nuevo sueño",
    "La mejor manera de apreciar tu trabajo es imaginarte sin él",
    "La actitud es una pequeña cosa que marca una gran diferencia",
    "Si quieres que algo se haga, dáselo a una persona ocupada",
    "El pesimista se queja del viento; el optimista espera que cambie; el realista ajusta las velas",
    "La única limitación en tu vida es aquella que te pones tú mismo",
    "El coraje es resistencia al miedo, dominio del miedo, no ausencia de miedo",
    "La vida es una aventura audaz o nada en absoluto",
    "No hay sustituto para la experiencia",
    "La vida no se trata de esperar a que pase la tormenta, se trata de aprender a bailar bajo la lluvia",
    "El mañana es el día más importante en la vida. Llega a la medianoche. Es perfecto cuando llega y se pone en nuestras manos. Espera que hayamos aprendido algo de ayer",
    "La mente es como un paracaídas, solo funciona si se abre",
    "Sé el cambio que quieres ver en el mundo",
    "No juzgues cada día por la cosecha que recoges, sino por las semillas que siembras",
    "Lo que haces hoy es importante, porque estás invirtiendo un día de tu vida",
    "El éxito no es una casualidad. Es trabajo duro, perseverancia, aprendizaje, estudio, sacrificio y, sobre todo, amor por lo que estás haciendo o aprendiendo a hacer",
    "El propósito de la vida es una vida con propósito",
    "No dejes que el miedo a perder sea mayor que la emoción de ganar",
    "Cree que puedes y ya estás a medio camino",
    "La felicidad no es una estación a la que se llega, sino una forma de viajar",
    "No eres derrotado cuando pierdes, eres derrotado cuando te rindes",
    "El secreto para salir adelante es empezar",
    "La vida te pondrá obstáculos, pero los límites los pones tú",
    "Donde no hay lucha, no hay fuerza",
    "La paciencia es la clave del éxito",
    "La oportunidad golpea, pero también tienes que abrir la puerta",
    "El optimismo es la fe que conduce al logro. Nada se puede hacer sin esperanza y confianza",
    "No te arrepientas de nada. La gente buena te da felicidad, la gente mala te da lecciones y la gente excelente te da recuerdos",
    "La vida es demasiado corta para resentimientos",
    "La sabiduría no es un producto de la escolaridad, sino del intento de toda una vida de adquirirla",
    "Haz que hoy cuente",
    "No hay éxito sin dificultad",
    "Cada día es una nueva oportunidad para cambiar tu vida",
    "La inspiración viene de dentro",
    "La mejor forma de empezar es empezar",
    "La única forma de crecer es salir de tu zona de confort",
    "Sé la persona que hace que los demás se sientan incluidos",
    "Tu valor no disminuye por la incapacidad de otros para verlo",
    "La vida es un viaje, disfrútalo",
    "No hay un camino fácil para la libertad en ninguna parte, y muchos de nosotros tendremos que pasar por el valle de la sombra de la muerte una y otra vez antes de que alcancemos la cima de la montaña de nuestro deseo",
    "La perseverancia es la madre de la buena suerte",
    "El universo no te pide que seas perfecto, solo te pide que seas tú",
    "La vida es como un espejo, si le sonríes, te devuelve la sonrisa",
    "La verdadera felicidad no es el resultado de la riqueza o el lujo, sino el resultado de la tranquilidad y el trabajo",
    "La vida es una colección de momentos, vívelos",
    "Lo que te asusta es una señal de que necesitas crecer",
    "El amor es la fuerza más poderosa del universo",
    "El respeto es una calle de doble sentido",
    "La clave de la vida es el equilibrio",
    "No te canses de dar. El día menos pensado la vida te lo devuelve",
    "La vida es un regalo, un privilegio, no un derecho",
    "La simplicidad es la forma de arte de la vida",
    "Un paso a la vez, una meta a la vez, un día a la vez",
    "La mente es el campo de batalla",
    "La risa es el sonido del alma",
    "La grandeza empieza con la decisión de intentarlo",
    "El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace",
    "La mejor manera de predecir el futuro es inventarlo",
    "La vida no se mide por la cantidad de veces que respiramos, sino por los momentos que nos quitan el aliento",
    "La educación es el pasaporte al futuro, porque el mañana pertenece a aquellos que se preparan para él hoy",
    "La gratitud es la memoria del corazón",
    "No podemos ayudar a todos, pero todos podemos ayudar a alguien",
    "La verdadera medida de un hombre no es cómo se comporta en momentos de comodidad y conveniencia, sino cómo se comporta en momentos de controversia y desafío",
    "La vida es un espejo que te devuelve lo que le muestras",
    "Tu actitud, no tu aptitud, determinará tu altitud",
    "No te conformes con lo bueno cuando puedes ser grande",
    "Sé la mejor versión de ti mismo",
    "El éxito no es una opción, es un resultado de la elección",
    "El esfuerzo continuo, no la fuerza o la inteligencia, es la clave para liberar nuestro potencial",
    "La vida es lo que pasa mientras estás ocupado haciendo otros planes",
    "No te tomes la vida demasiado en serio. Nunca saldrás vivo de ella",
    "El mundo necesita más amor y menos odio",
    "La belleza está en los ojos del que mira",
    "La paciencia es la madre de todas las virtudes",
    "La creatividad es la capacidad de introducir orden en el caos",
    "La vida es un jardín, cultívala",
    "El camino hacia la grandeza no es fácil",
    "La única persona en la que estás destinado a convertirte es la persona que decidas ser",
    "La felicidad es una dirección, no un lugar",
    "La sabiduría comienza en el asombro",
    "Lo que siembras, cosechas",
    "El coraje es la gracia bajo presión",
    "No te arrepientas de un día en tu vida: los buenos días te dan felicidad, los malos días te dan experiencia, los peores días te dan lecciones y los mejores días te dan recuerdos",
    "La vida es para vivirla, no para mirarla",
    "El optimismo es el imán de la felicidad",
    "La vida es un rompecabezas, arma tus piezas",
    "Tu potencial es ilimitado",
    "Cada nuevo día es un nuevo comienzo",
    "La mejor manera de aprender es haciendo",
    "No hay mejor maestro que la experiencia",
    "La vida es un eco, lo que envías, regresa",
    "La disciplina es la clave del éxito a largo plazo",
    "Sé la mejor versión de ti mismo, no una copia de alguien más",
    "El éxito es el resultado de la perfección, el trabajo duro, el aprendizaje de los errores, la lealtad y la persistencia",
    "La vida es un viaje, no un destino",
    "No te limites. Muchos se limitan a lo que creen que pueden hacer. Puedes ir tan lejos como tu mente te lo permita. Lo que crees, lo puedes lograr",
    "La felicidad es una forma de viajar, no un destino",
    "La simplicidad es la clave de la elegancia",
    "La mejor inversión es en uno mismo",
    "La verdadera libertad está en la mente",
    "El poder reside en la acción",
    "La vida es un regalo, úsalo sabiamente",
    "La motivación es lo que te pone en marcha. El hábito es lo que te mantiene",
    "No cuentes los años, haz que los años cuenten",
    "El futuro está en tus manos",
    "La mejor venganza es ser feliz",
    "La vida es un experimento. Cuantos más experimentos hagas, mejor",
    "El éxito es un viaje, no un destino",
    "No dejes que el ruido de las opiniones de los demás ahogue tu propia voz interior",
    "La mente es el límite",
    "El único modo de hacer un gran trabajo es amar lo que haces",
    "La vida es como un libro, si no viajas, solo lees una página",
    "La persistencia es la cualidad esencial para el éxito",
    "Cada día es una nueva oportunidad para ser mejor que ayer",
    "La vida es una oportunidad, aprovéchala",
    "La felicidad es algo que se multiplica cuando se divide",
    "La gratitud es el principio de la abundancia",
    "No esperes, nunca va a ser el momento adecuado",
    "La vida es un jardín, siembra semillas de bondad",
    "Sé la excepción, no la regla",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día",
    "La vida es una canción, canta tu propia melodía",
    "Tu potencial es infinito",
    "La mejor vista viene después de la escalada más difícil",
    "Lo que haces hoy puede mejorar todos tus mañanas",
    "La vida es lo que tú haces de ella, siempre lo ha sido, siempre lo será",
    "El mañana es un misterio, el hoy es un regalo",
    "La grandeza se logra con pequeños pasos cada día",
    "La verdadera alegría radica en el esfuerzo, en la emoción del esfuerzo y en la realización del objetivo",
    "La vida es un arte, píntala a tu gusto",
    "La resiliencia es clave, levántate cada vez que caigas",
    "El secreto de la existencia no es solo vivir, sino saber para qué se vive",
    "La vida es un eco, lo que envías, te regresa",
    "No te compares con los demás, compárate contigo mismo",
    "La única forma de crecer es salir de tu zona de confort",
    "La felicidad es una mariposa, cuanto más la persigues, más se te escapa. Pero si te concentras en otras cosas, viene y se posa suavemente en tu hombro",
    "La fe no hace que las cosas sean fáciles, las hace posibles",
    "El éxito es la realización progresiva de un objetivo digno",
    "La vida es una aventura audaz o nada",
    "Lo importante no es la meta, sino el camino",
    "La mejor inversión es en ti mismo",
    "La vida es un lienzo en blanco, y tú eres el artista. Píntala de color"
  ];
  
  // Función para seleccionar una frase aleatoria
  function obtenerFraseAleatoria() {
    const indiceAleatorio = Math.floor(Math.random() * frases.length);
    return frases[indiceAleatorio];
  }
  
  // Configuración de CORS para permitir solicitudes desde cualquier origen
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
  
  // Manejador de solicitudes (fetch event)
  export default {
    async fetch(request) {
      // Manejo de pre-vuelos OPTIONS para CORS
      if (request.method === "OPTIONS") {
        return new Response(null, {
          status: 204, // No Content
          headers: corsHeaders
        });
      }
  
      // Solo respondemos a solicitudes GET
      if (request.method === "GET") {
        const fraseAleatoria = obtenerFraseAleatoria();
  
        // Crea un objeto JSON con la frase
        const responseBody = {
          frase: fraseAleatoria
        };
  
        // Retorna la respuesta JSON con las cabeceras CORS
        return new Response(JSON.stringify(responseBody), {
          headers: {
            "Content-Type": "application/json",
            ...corsHeaders // Añade las cabeceras CORS aquí
          }
        });
      }
  
      // Para cualquier otro método HTTP no permitido
      return new Response("Método no permitido", {
        status: 405,
        headers: corsHeaders // Asegúrate de incluir CORS también en respuestas de error
      });
    },
  };